### ISSUE TITLE
Possible variable issue

### ISSUE THREAD

**Issue by StevenDvn** [Windos/AzSpeedOps#1]
https://github.com/Windos/AzSpeedOps/blob/317bb28c30f7f3720e8c24fdc0e8ca946cd834a8/build.ps1#L57

Shouldn't "$res" be "$Results" for this to work properly?

**Comment by Windos** [comment]
You're absolutely right, I'l going to be working on this over this weekend and will fix this in one of the commits.

Thanks for the heads up!
